title: Alexandr Wolodarkij
description: "Indie game developer and AI optimist."
url: ""
baseurl: ""
theme: jekyll-theme-minimal
show_downloads: false
google_analytics:
header_pages:
  - about.md
  - projects.md
  - blog.md

author:
  name: Alexandr Wolodarkij
  email: wolodarskij@octobernight.games
  location: Berlin, Germany
  summary: "Indie game developer and AI optimist."
navigation:
  - text: About
    url: /about
  - text: Projects
    url: /projects
  - text: Blog
    url: /blog
  - text: Contact
    url: /#ping

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

plugins:
  - jekyll-feed
  - jekyll-seo-tag